using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MC_BE.Migrations
{
    public partial class FixForumLearningAfterPR32 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS forum_topics (
    "TopicID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(120) NOT NULL,
    "Description" text,
    "Icon" character varying(50),
    "OrderIndex" integer NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'ACTIVE',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_forum_topics" PRIMARY KEY ("TopicID")
);

CREATE TABLE IF NOT EXISTS speaking_submissions (
    "SubmissionID" integer GENERATED BY DEFAULT AS IDENTITY,
    "LessonID" integer NOT NULL,
    "LearnerID" integer NOT NULL,
    "AudioUrl" character varying(1000) NOT NULL,
    "Note" text,
    "Status" text NOT NULL DEFAULT 'SUBMITTED',
    "Score" numeric(5,2),
    "Feedback" text,
    "GradedByID" integer,
    "GradedAt" timestamp with time zone,
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_speaking_submissions" PRIMARY KEY ("SubmissionID"),
    CONSTRAINT "FK_speaking_submissions_lessons_LessonID" FOREIGN KEY ("LessonID") REFERENCES lessons ("LessonID") ON DELETE CASCADE,
    CONSTRAINT "FK_speaking_submissions_users_GradedByID" FOREIGN KEY ("GradedByID") REFERENCES users ("UserID") ON DELETE RESTRICT,
    CONSTRAINT "FK_speaking_submissions_users_LearnerID" FOREIGN KEY ("LearnerID") REFERENCES users ("UserID") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS forum_posts (
    "PostID" integer GENERATED BY DEFAULT AS IDENTITY,
    "TopicID" integer NOT NULL,
    "AuthorID" integer NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Content" text NOT NULL,
    "ImageUrl" text,
    "ViewsCount" integer NOT NULL DEFAULT 0,
    "ReactionsCount" integer NOT NULL DEFAULT 0,
    "CommentsCount" integer NOT NULL DEFAULT 0,
    "ReportsCount" integer NOT NULL DEFAULT 0,
    "Status" character varying(30) NOT NULL DEFAULT 'PUBLISHED',
    "IsPinned" boolean NOT NULL,
    "IsLocked" boolean NOT NULL,
    "IsAnonymous" boolean NOT NULL,
    "RestoredAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_forum_posts" PRIMARY KEY ("PostID"),
    CONSTRAINT "FK_forum_posts_forum_topics_TopicID" FOREIGN KEY ("TopicID") REFERENCES forum_topics ("TopicID") ON DELETE RESTRICT,
    CONSTRAINT "FK_forum_posts_users_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES users ("UserID") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS forum_comments (
    "CommentID" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostID" integer NOT NULL,
    "AuthorID" integer NOT NULL,
    "ParentCommentID" integer,
    "DepthLevel" integer NOT NULL DEFAULT 1,
    "Content" text NOT NULL,
    "ImageUrl" text,
    "IsAnonymous" boolean NOT NULL DEFAULT FALSE,
    "ReactionsCount" integer NOT NULL DEFAULT 0,
    "ReportsCount" integer NOT NULL DEFAULT 0,
    "Status" character varying(30) NOT NULL DEFAULT 'ACTIVE',
    "RestoredAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_forum_comments" PRIMARY KEY ("CommentID"),
    CONSTRAINT "FK_forum_comments_forum_comments_ParentCommentID" FOREIGN KEY ("ParentCommentID") REFERENCES forum_comments ("CommentID") ON DELETE RESTRICT,
    CONSTRAINT "FK_forum_comments_forum_posts_PostID" FOREIGN KEY ("PostID") REFERENCES forum_posts ("PostID") ON DELETE CASCADE,
    CONSTRAINT "FK_forum_comments_users_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES users ("UserID") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS forum_reactions (
    "ReactionID" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserID" integer NOT NULL,
    "TargetType" character varying(20) NOT NULL,
    "PostID" integer,
    "CommentID" integer,
    "ReactionType" character varying(20) NOT NULL DEFAULT 'LIKE',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_forum_reactions" PRIMARY KEY ("ReactionID"),
    CONSTRAINT "FK_forum_reactions_forum_comments_CommentID" FOREIGN KEY ("CommentID") REFERENCES forum_comments ("CommentID") ON DELETE CASCADE,
    CONSTRAINT "FK_forum_reactions_forum_posts_PostID" FOREIGN KEY ("PostID") REFERENCES forum_posts ("PostID") ON DELETE CASCADE,
    CONSTRAINT "FK_forum_reactions_users_UserID" FOREIGN KEY ("UserID") REFERENCES users ("UserID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS forum_reports (
    "ReportID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReporterID" integer NOT NULL,
    "TargetType" character varying(20) NOT NULL,
    "PostID" integer,
    "CommentID" integer,
    "Reason" character varying(50) NOT NULL,
    "Details" character varying(500),
    "Status" character varying(20) NOT NULL DEFAULT 'PENDING',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ResolvedAt" timestamp with time zone,
    "ResolvedByID" integer,
    CONSTRAINT "PK_forum_reports" PRIMARY KEY ("ReportID"),
    CONSTRAINT "FK_forum_reports_forum_comments_CommentID" FOREIGN KEY ("CommentID") REFERENCES forum_comments ("CommentID") ON DELETE CASCADE,
    CONSTRAINT "FK_forum_reports_forum_posts_PostID" FOREIGN KEY ("PostID") REFERENCES forum_posts ("PostID") ON DELETE CASCADE,
    CONSTRAINT "FK_forum_reports_users_ReporterID" FOREIGN KEY ("ReporterID") REFERENCES users ("UserID") ON DELETE RESTRICT,
    CONSTRAINT "FK_forum_reports_users_ResolvedByID" FOREIGN KEY ("ResolvedByID") REFERENCES users ("UserID") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_forum_comments_AuthorID" ON forum_comments ("AuthorID");

CREATE INDEX IF NOT EXISTS "IX_forum_comments_ParentCommentID" ON forum_comments ("ParentCommentID");

CREATE INDEX IF NOT EXISTS "IX_forum_comments_PostID" ON forum_comments ("PostID");

CREATE INDEX IF NOT EXISTS "IX_forum_comments_Status" ON forum_comments ("Status");

CREATE INDEX IF NOT EXISTS "IX_forum_posts_AuthorID" ON forum_posts ("AuthorID");

CREATE INDEX IF NOT EXISTS "IX_forum_posts_Status" ON forum_posts ("Status");

CREATE INDEX IF NOT EXISTS "IX_forum_posts_TopicID" ON forum_posts ("TopicID");

CREATE INDEX IF NOT EXISTS "IX_forum_reactions_CommentID" ON forum_reactions ("CommentID");

CREATE INDEX IF NOT EXISTS "IX_forum_reactions_PostID" ON forum_reactions ("PostID");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_forum_reactions_UserID_TargetType_PostID_CommentID" ON forum_reactions ("UserID", "TargetType", "PostID", "CommentID");

CREATE INDEX IF NOT EXISTS "IX_forum_reports_CommentID" ON forum_reports ("CommentID");

CREATE INDEX IF NOT EXISTS "IX_forum_reports_PostID" ON forum_reports ("PostID");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_forum_reports_ReporterID_TargetType_PostID_CommentID" ON forum_reports ("ReporterID", "TargetType", "PostID", "CommentID");

CREATE INDEX IF NOT EXISTS "IX_forum_reports_ResolvedByID" ON forum_reports ("ResolvedByID");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_forum_topics_Slug" ON forum_topics ("Slug");

CREATE INDEX IF NOT EXISTS "IX_speaking_submissions_GradedByID" ON speaking_submissions ("GradedByID");

CREATE INDEX IF NOT EXISTS "IX_speaking_submissions_LearnerID_LessonID" ON speaking_submissions ("LearnerID", "LessonID");

CREATE INDEX IF NOT EXISTS "IX_speaking_submissions_LessonID" ON speaking_submissions ("LessonID");

CREATE INDEX IF NOT EXISTS "IX_speaking_submissions_Status" ON speaking_submissions ("Status");

""");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Cố tình để trống: 
            // Vì migration này được dùng để đồng bộ lại Model Snapshot với Database (bảng đã tồn tại),
            // việc DROP TABLE ở hàm Down() có thể vô tình xóa mất dữ liệu Forum hiện có trên Production khi ai đó gọi lệnh revert.
            // Nếu đây là một DB mới hoàn toàn, bạn có thể tự quản lý việc drop thủ công nếu cần.
        }
    }
}

